development:     #
  adapter: postgresql
  encoding: unicode
  database: pratic
  pool: 5
  username: postgres
  password: di03051999
  host: localhost
  port: 5432

test:            #
  adapter: postgresql
  encoding: unicode
  database: pratic
  pool: 5
  username: postgres	
  password: di03051999
  host: localhost
  port: 5432

production:      #
  adapter: postgresql
  encoding: unicode
  database: sudamericanas
  pool: 5
  username: postgres
  password: di03051999
  host: localhost
  port: 5432
